import { withBaseUrl } from "./asset-url";

const meiElements = new Set([
    "accid",
    "annot",
    "app",
    "arpeg",
    "artic",
    "beam",
    "beamSpan",
    "beatRpt",
    "bracketSpan",
    "breath",
    "bTrem",
    "caesura",
    "choice",
    "chord",
    "clef",
    "cpMark",
    "custos",
    "dir",
    "dynam",
    "ending",
    "f",
    "fb",
    "fermata",
    "fing",
    "fTrem",
    "gliss",
    "graceGrp",
    "hairpin",
    "halfmRpt",
    "harm",
    "keySig",
    "layer",
    "layerDef",
    "lb",
    "lv",
    "mdiv",
    "measure",
    "meterSig",
    "mordent",
    "mRest",
    "mRpt",
    "mRpt2",
    "mSpace",
    "multiRest",
    "multiRpt",
    "note",
    "octave",
    "ornam",
    "pb",
    "pedal",
    "phrase",
    "reh",
    "rend",
    "repeatMark",
    "rest",
    "sb",
    "score",
    "scoreDef",
    "section",
    "slur",
    "staff",
    "staffDef",
    "syl",
    "symbol",
    "tempo",
    "text",
    "tie",
    "trill",
    "tuplet",
    "tupletSpan",
    "turn",
    "verse",
]);

export function iconFor(
    element: string,
): string {
    const normalized = meiElements.has(element) ? element : "missing";
    return withBaseUrl(`icons/mei/${normalized}.png`);
}
